

services:
  php:
    build:
      context: ./config/php
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "${DB_PASSCHOICE}"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

